services:
#MYSQL_USER 	MySQL database user to create during the first initialization. 	nil
#MYSQL_PASSWORD 	Password for the MySQL database user to create during the first initialization. 	nil
#MYSQL_DATABASE
  mysql:
    container_name: mysql
    image: 'bitnami/mysql:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=exb021205
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=appuser
      - MYSQL_DATABASE=app
    volumes:
      - ./data:/bitnami/mysql/data
  nginx:
    container_name: nginx
    image: 'bitnami/nginx:latest'
    depends_on:
      - phpfpm
    #networks:
    #  - app-tier
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./conf/app.conf:/opt/bitnami/nginx/conf/server_blocks/app.conf
      - ./app:/var/www/html

  phpfpm:
    container_name: phpfpm
    image: 'bitnami/php-fpm:latest'
    # networks:
    #   - app-tier
    volumes:
      - ./app:/var/www/html
